# Phase 1 - Week 1 - Day 2 AM - Math for Machine Learning - Vector & Matrix

# A. Vector

## A.1 - Define A Vector

In [1]:
# Import library

import numpy as np

In [2]:
# Define a vector

a = [1, 2, 3]
vect_a = np.array(a)
vect_a

array([1, 2, 3])

In [3]:
# Check type of the variable and vector size

print('Type : ', type(vect_a))
print('Size : ', vect_a.shape)

Type :  <class 'numpy.ndarray'>
Size :  (3,)


## A.2 - Vector Norm

In [4]:
# Find the vector norm

b = [4, 3]
vect_b = np.array(b)

print('L1 - Manhattan Distance')
print(np.linalg.norm(vect_b, 1))
print('')

print('L2 - Euclidean Distance')
print(np.linalg.norm(vect_b))
print(np.linalg.norm(vect_b, 2))

L1 - Manhattan Distance
7.0

L2 - Euclidean Distance
5.0
5.0


## A.3 - Arithmetic Operations

In [5]:
# Arithmetic operations with a scalar (addition, substraction, multiplication, and division)

c = [1, 2, 3]
vect_c = np.array(c)

print('Addition       : ', vect_c + 2)
print('Substraction   : ', vect_c - 2)
print('Multiplication : ', vect_c * 2)
print('Division       : ', vect_c / 2)

Addition       :  [3 4 5]
Substraction   :  [-1  0  1]
Multiplication :  [2 4 6]
Division       :  [0.5 1.  1.5]


In [6]:
# Arithmetic operations between vectors (addition, substraction, multiplication, and division)

d = [1, 2, 3]
e = [4, 5, 6]

vect_d = np.array(d)
vect_e = np.array(e)

print('Addition     : ', vect_d + vect_e)
print('')

print('Substraction : ', vect_d - vect_e)
print('')

print('Division     : ', vect_d / vect_e)
print('')

print('Multiplication (element-wise) : ', vect_d * vect_e)
print('')

print('Multiplication (dot product)  : ')
print('Syntax 1 : ', vect_d @ vect_e)
print('Syntax 2 : ', vect_d.dot(vect_e))
print('Syntax 3 : ', np.dot(vect_d, vect_e))

Addition     :  [5 7 9]

Substraction :  [-3 -3 -3]

Division     :  [0.25 0.4  0.5 ]

Multiplication (element-wise) :  [ 4 10 18]

Multiplication (dot product)  : 
Syntax 1 :  32
Syntax 2 :  32
Syntax 3 :  32


## A.4 - Cosine Similarity

In [7]:
# Cosine similarity

f = [8, 0]
g = [6, 2]

vect_f = np.array(f)
vect_g = np.array(g)

cos_theta = (vect_f @ vect_g) / (np.linalg.norm(vect_f) * np.linalg.norm(vect_g))

print('Cosine Similarity : ', cos_theta)

Cosine Similarity :  0.9486832980505138


In [8]:
# Find the radian and the degree

radian = np.arccos(cos_theta)
degree = np.degrees(radian)

print('Radian : ', radian)
print('Degree : ', degree)

Radian :  0.3217505543966423
Degree :  18.434948822922017


## A.5 - Case Study

```
teks_1 = saya pergi ke rumah kakek saya
teks_2 = saya pergi ke rumah nenek saya
```

In [9]:
# Find the similarity

t1 = [2, 1, 1, 1, 1, 0]
t2 = [2, 1, 1, 1, 0, 1]

vect_t1 = np.array(t1)
vect_t2 = np.array(t2)

cos_theta = (vect_t1 @ vect_t2) / (np.linalg.norm(vect_t1) * np.linalg.norm(vect_t2))

print('Cosine Similarity : ', cos_theta)

Cosine Similarity :  0.8749999999999998


# B. Matrix

## B.1 - Define A Matrix

In [10]:
# Define a matrix

A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

matrix_A = np.array(A)
matrix_A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# Check type of the variable and matrix size

print('Type : ', type(matrix_A))
print('Size : ', matrix_A.shape)

Type :  <class 'numpy.ndarray'>
Size :  (3, 3)


In [12]:
# Type of matrix

print('Upper triangular matrix : \n', np.triu(matrix_A))
print('')

print('Lower triangular matrix : \n', np.tril(matrix_A))
print('')

print('Diagonal matrix         : \n', np.diag(matrix_A))
print('')

print('Identity matrix (3,3)   : \n', np.eye(3, 3))
print('')

Upper triangular matrix : 
 [[1 2 3]
 [0 5 6]
 [0 0 9]]

Lower triangular matrix : 
 [[1 0 0]
 [4 5 0]
 [7 8 9]]

Diagonal matrix         : 
 [1 5 9]

Identity matrix (3,3)   : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



## B.2 - Arithmetic Operations

In [13]:
# Arithmetic operations with a scalar (addition, substraction, multiplication, and division)

B = [[1, 2],
     [3, 4],
     [5, 6]]

matrix_B = np.array(B)

print('Addition       : \n', matrix_B + 2)
print('')

print('Substraction   : \n', matrix_B - 2)
print('')

print('Multiplication : \n', matrix_B * 2)
print('')

print('Division       : \n', matrix_B / 2)
print('')

Addition       : 
 [[3 4]
 [5 6]
 [7 8]]

Substraction   : 
 [[-1  0]
 [ 1  2]
 [ 3  4]]

Multiplication : 
 [[ 2  4]
 [ 6  8]
 [10 12]]

Division       : 
 [[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]



In [14]:
# Arithmetic operations between matrices (addition, substraction, multiplication, and division)

C = [[1, 2],
     [3, 4],
     [5, 6]]

matrix_C = np.array(C)

D = [[7, 8],
     [9, 10],
     [11, 12]]
matrix_D = np.array(D)

print('Addition     : \n', matrix_C + matrix_D)
print('')

print('Substraction : \n', matrix_C - matrix_D)
print('')

print('Division     : \n', matrix_C / matrix_D)
print('')

print('Multiplication (element-wise) : \n', matrix_C * matrix_D)
print('')

Addition     : 
 [[ 8 10]
 [12 14]
 [16 18]]

Substraction : 
 [[-6 -6]
 [-6 -6]
 [-6 -6]]

Division     : 
 [[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]

Multiplication (element-wise) : 
 [[ 7 16]
 [27 40]
 [55 72]]



In [15]:
# Multiplication (dot product) between matrices

E = [[1, 2],
     [3, 4],
     [5, 6]]

F = [[1, 2],
     [3, 4]]

matrix_E = np.array(E)
matrix_F = np.array(F)

print('Multiplication (dot product)')

print('Syntax 1 : \n', matrix_E @ matrix_F)
print('')

print('Syntax 2 : \n', matrix_E.dot(matrix_F))
print('')

print('Syntax 3 : \n', np.dot(matrix_E, matrix_F))
print('')

Multiplication (dot product)
Syntax 1 : 
 [[ 7 10]
 [15 22]
 [23 34]]

Syntax 2 : 
 [[ 7 10]
 [15 22]
 [23 34]]

Syntax 3 : 
 [[ 7 10]
 [15 22]
 [23 34]]



In [16]:
# Multiplication between a matrix and an identity matrix

G = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

matrix_G = np.array(G)
print('Original matrix : \n', matrix_G)
print('')

matrix_I = np.eye(3, 3)
print('Identity matrix : \n', matrix_I)
print('')

print('Multiplication result : \n', matrix_G @ matrix_I)

Original matrix : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Identity matrix : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Multiplication result : 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## B.3 - Transpose & Determinant

In [17]:
# Transpose of a matrix

H = [[1, 2],
     [3, 4],
     [5, 6]]

matrix_H = np.array(H)

print('Original matrix : \n', matrix_H)
print('')

print('Transpose matrix : \n', matrix_H.T)
print('')

Original matrix : 
 [[1 2]
 [3 4]
 [5 6]]

Transpose matrix : 
 [[1 3 5]
 [2 4 6]]



In [18]:
# Determinant of a matrix

J = [[1, 2],
     [3, 4]]

K = [[10, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

matrix_J = np.array(J)
matrix_K = np.array(K)

print('Determinant of matrix_H : ', np.linalg.det(matrix_J))
print('Determinant of matrix_J : ', np.linalg.det(matrix_K))

Determinant of matrix_H :  -2.0000000000000004
Determinant of matrix_J :  -27.0


## B.4 - Inverse

In [19]:
# Inverse of matrix

L = [[1, 2],
     [3, 4]]

matrix_L = np.array(L)
inverse_matrix_L = np.linalg.inv(matrix_L)

print('Original matrix : \n', matrix_L)
print('')

print('Inverse matrix  : \n', inverse_matrix_L)
print('')

print('Multiplication between a matrix and its inverse : \n', matrix_L @ inverse_matrix_L)

Original matrix : 
 [[1 2]
 [3 4]]

Inverse matrix  : 
 [[-2.   1. ]
 [ 1.5 -0.5]]

Multiplication between a matrix and its inverse : 
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## B.5 - Eigendecomposition

In [20]:
# Find the eigenvalues and the eigenvectors from a matrix

M = [[2, 0],
     [0, 3]]

matrix_M = np.array(M)

eigenvalues, eigenvectors = np.linalg.eig(matrix_M)

print('Eigenvalues  : \n', eigenvalues)
print('')

print('Eigenvectors : \n', eigenvectors)
print('')

Eigenvalues  : 
 [2. 3.]

Eigenvectors : 
 [[1. 0.]
 [0. 1.]]



In [21]:
# Reconstruct the matrix from its eigenvalues and eigenvectors

matrix_reconstruct = eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)

print('Matrix reconstruct : \n', matrix_reconstruct)
print('')

print('Equality check : ', np.array_equal(matrix_M, matrix_reconstruct))

Matrix reconstruct : 
 [[2. 0.]
 [0. 3.]]

Equality check :  True


## B.6 - Usecase : Page Rank

PageRank (developed by Larry Page and Sergey Brin) revolutionized web search by generating a ranked list of web pages based on the underlying connectivity of the web. The PageRank algorithm is based on an ideal random web surfer who, when reaching a page, goes to the next page by clicking on a link. The surfer has equal probability of clicking any link on the page and, when reaching a page with no links, has equal probability of moving to any other page by typing in its URL. **The PageRank is the ranked order of the pages from the most to the least probable page the surfer will be viewing.**

For example, suppose there are 4 webs like the image below.

<img src='https://gowrishankar.info/blog/eigenvalue-eigenvector-eigenspace-and-implementation-of-googles-pagerank-algorithm/links.png'>

To calculate the pagerank, we need to create an adjancecy matrix.

<img src='https://gowrishankar.info/blog/eigenvalue-eigenvector-eigenspace-and-implementation-of-googles-pagerank-algorithm/m1.png'>

In [22]:
# Step 1 : Define the adjacency matrix

M = np.array([
    # 1   2     3     4
    [0,   1/3,  1/3,  1/3],   # From 1
    [1/2, 0,    0,    1/2],   # From 2
    [0,   0,    0,    1],     # From 3
    [0,   1/2,  1/2,  0]      # From 4
])
M

array([[0.        , 0.33333333, 0.33333333, 0.33333333],
       [0.5       , 0.        , 0.        , 0.5       ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.        , 0.5       , 0.5       , 0.        ]])

In [23]:
# Step 2 : Calculate eigenvectors and eigenvalues

eigenvalues, eigenvectors = np.linalg.eig(M.T)
print('Eigen Values : ')
print(eigenvalues)
print('')

print('Eigen Vectors : ')
print(eigenvectors)
print('')

Eigen Values : 
[ 1.00000000e+00 -9.17517095e-02 -9.08248290e-01 -6.82897983e-17]

Eigen Vectors : 
[[-2.22988244e-01 -8.25340062e-01  2.62323812e-01 -8.01783726e-01]
 [-4.45976488e-01  1.51452723e-01 -4.76510307e-01  1.25887458e-16]
 [-4.45976488e-01  1.51452723e-01 -4.76510307e-01  2.67261242e-01]
 [-7.43294146e-01  5.22434615e-01  6.90696802e-01  5.34522484e-01]]



In [24]:
# Step 3 : Find eigenvector that has the largest eigenvalue

index_largest_eigenvalues = np.argmax(eigenvalues)
largest_eigenvalues = eigenvalues[index_largest_eigenvalues]
largest_eigenvectors = eigenvectors[:, index_largest_eigenvalues]

print('Index largest Eigen Values : ', index_largest_eigenvalues)
print('Largest Eigen Values       : ', largest_eigenvalues)
print('Largest Eigen Vectors      : ', largest_eigenvectors)

Index largest Eigen Values :  0
Largest Eigen Values       :  1.0000000000000004
Largest Eigen Vectors      :  [-0.22298824 -0.44597649 -0.44597649 -0.74329415]


In [25]:
# Step 4 : Get the ranked orders of the pages

largest_eigenvectors = largest_eigenvectors.real
ranks = largest_eigenvectors / largest_eigenvectors.sum()
ranks = np.argsort(ranks)[::-1]+1
ranks

array([4, 3, 2, 1])

**CONCLUSION:**

1. Page `D` is a popular page because all other pages are reffering to page `D`.

2. Page `C` & page `B` are equally visited because they both are reffered by 2 other pages.

3. Page `A` is an the least popular page because it is reffered only by page `B`.